-- Add more cities for all states
INSERT INTO cities (name, state) VALUES
  -- Additional California Cities
  ('Beverly Hills', 'California'),
  ('Newport Beach', 'California'),
  ('Laguna Beach', 'California'),
  ('San Clemente', 'California'),
  ('Huntington Beach', 'California'),
  ('Malibu', 'California'),
  ('Pasadena', 'California'),
  ('Santa Rosa', 'California'),
  ('Ventura', 'California'),
  ('San Luis Obispo', 'California'),
  ('Temecula', 'California'),
  ('Carlsbad', 'California'),
  ('La Jolla', 'California'),
  ('Del Mar', 'California'),
  ('Coronado', 'California'),

  -- Additional New York Cities
  ('The Hamptons', 'New York'),
  ('Westchester', 'New York'),
  ('Lake George', 'New York'),
  ('Finger Lakes', 'New York'),
  ('Woodbury', 'New York'),
  ('Garden City', 'New York'),
  ('Southampton', 'New York'),
  ('East Hampton', 'New York'),
  ('Bridgehampton', 'New York'),
  ('Sag Harbor', 'New York'),

  -- Additional Florida Cities
  ('Boca Raton', 'Florida'),
  ('Palm Beach Gardens', 'Florida'),
  ('Jupiter', 'Florida'),
  ('Delray Beach', 'Florida'),
  ('Coral Gables', 'Florida'),
  ('Winter Park', 'Florida'),
  ('St. Petersburg Beach', 'Florida'),
  ('Clearwater Beach', 'Florida'),
  ('Marco Island', 'Florida'),
  ('Sanibel Island', 'Florida'),
  ('Amelia Island', 'Florida'),
  ('Ponte Vedra Beach', 'Florida'),
  ('Palm Coast', 'Florida'),
  ('Boca Grande', 'Florida'),
  ('Fisher Island', 'Florida'),

  -- Additional Texas Cities
  ('The Woodlands', 'Texas'),
  ('Sugar Land', 'Texas'),
  ('Katy', 'Texas'),
  ('Frisco', 'Texas'),
  ('McKinney', 'Texas'),
  ('Allen', 'Texas'),
  ('Southlake', 'Texas'),
  ('Highland Park', 'Texas'),
  ('University Park', 'Texas'),
  ('West Lake Hills', 'Texas'),
  ('Round Rock', 'Texas'),
  ('New Braunfels', 'Texas'),
  ('Georgetown', 'Texas'),
  ('Cedar Park', 'Texas'),
  ('Fredericksburg', 'Texas'),

  -- Additional Massachusetts Cities
  ('Wellesley', 'Massachusetts'),
  ('Weston', 'Massachusetts'),
  ('Concord', 'Massachusetts'),
  ('Lexington', 'Massachusetts'),
  ('Newton', 'Massachusetts'),
  ('Brookline', 'Massachusetts'),
  ('Marblehead', 'Massachusetts'),
  ('Manchester-by-the-Sea', 'Massachusetts'),
  ('Rockport', 'Massachusetts'),
  ('Newburyport', 'Massachusetts'),
  ('Falmouth', 'Massachusetts'),
  ('Chatham', 'Massachusetts'),
  ('Provincetown', 'Massachusetts'),
  ('Edgartown', 'Massachusetts'),
  ('Oak Bluffs', 'Massachusetts'),

  -- Additional Connecticut Cities
  ('Darien', 'Connecticut'),
  ('New Canaan', 'Connecticut'),
  ('Ridgefield', 'Connecticut'),
  ('Simsbury', 'Connecticut'),
  ('Avon', 'Connecticut'),
  ('Farmington', 'Connecticut'),
  ('Old Lyme', 'Connecticut'),
  ('Old Saybrook', 'Connecticut'),
  ('Litchfield', 'Connecticut'),
  ('Washington', 'Connecticut'),
  ('Kent', 'Connecticut'),
  ('Sharon', 'Connecticut'),
  ('Cornwall', 'Connecticut'),
  ('Salisbury', 'Connecticut'),
  ('Norfolk', 'Connecticut'),

  -- Additional Rhode Island Cities
  ('East Greenwich', 'Rhode Island'),
  ('Barrington', 'Rhode Island'),
  ('Bristol', 'Rhode Island'),
  ('Jamestown', 'Rhode Island'),
  ('Little Compton', 'Rhode Island'),
  ('Tiverton', 'Rhode Island'),
  ('South Kingstown', 'Rhode Island'),
  ('North Kingstown', 'Rhode Island'),
  ('Charlestown', 'Rhode Island'),
  ('Westerly', 'Rhode Island'),
  ('Middletown', 'Rhode Island'),
  ('Portsmouth', 'Rhode Island'),
  ('Warren', 'Rhode Island'),
  ('Cumberland', 'Rhode Island'),
  ('East Providence', 'Rhode Island')
ON CONFLICT (name, state, country) DO NOTHING;